import type { Metadata } from "next";
import "./globals.css";
import Header from "./_components/Header";
import Footer from "./_components/Footer";
import { dm_sans, dm_serif_text } from "./fonts";
import Navbar from "./_components/Navbar";
import { Category } from "@/types/Category";
import { fetchDataFromStrapi } from "@/services/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const categories: Category[] = await fetchDataFromStrapi("categories");

  return (
    <html
      lang="en"
      className={`${dm_sans.variable} ${dm_serif_text.variable} font-sans`}
    >
      <body>
        <main>
          <Header />
          <Navbar categories={categories} />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
