import "./globals.css";
import type { Metadata } from "next";
import { getCategories } from "@/data/loaders";
import Footer from "./_components/Footer";
import Header from "./_components/Header";
import Navbar from "./_components/Navbar";
import { dm_sans, dm_serif_text } from "./fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { data } = await getCategories();

  return (
    <html
      lang="en"
      className={`${dm_sans.variable} ${dm_serif_text.variable} font-sans`}
    >
      <body>
        <main>
          <Header />
          <Navbar categories={data} />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
