import './globals.css';
import type { Metadata } from 'next';
import { dm_sans, dm_serif_text } from '@/app/fonts';
import Footer from '@/components/custom/Footer';
import Header from '@/components/custom/Header';
import Navbar from '@/components/custom/Navbar';
import { getCategories } from '@/data/loaders';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { data } = await getCategories();

  return (
    <html
      lang="en"
      className={`${dm_sans.variable} ${dm_serif_text.variable} font-sans`}
    >
      <body>
        <main>
          <Header />
          <Navbar categories={data} />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
